#!/bin/bash

# Extra commands to be run during the applying of this theme go here

opt1="Light (Default)"
opt2="Light (Compact)"
opt3="Dark"
opt4="Dark (Compact)"
int=$(zenity --title "Theme Style" --height 380 --list --radiolist --text 'Select your Preferred Theme Style:' --column '' --column 'Style' TRUE "$opt1" FALSE "$opt2" FALSE "$opt3" FALSE "$opt4")
if [ "$int" = "Light (Default)" ] || [ -z "$int" ]; then
    gsettings set org.cinnamon.desktop.wm.preferences theme 'Adapta'
    gsettings set org.cinnamon.desktop.interface gtk-theme 'Adapta'
    gsettings set org.cinnamon.theme name 'Adapta'
fi
if [ "$int" = "Light (Compact)" ]; then
    gsettings set org.cinnamon.desktop.wm.preferences theme 'Adapta-Eta'
    gsettings set org.cinnamon.desktop.interface gtk-theme 'Adapta-Eta'
    gsettings set org.cinnamon.theme name 'Adapta'
fi
if [ "$int" = "Dark" ]; then
    gsettings set org.cinnamon.desktop.wm.preferences theme 'Adapta-Nokto'
    gsettings set org.cinnamon.desktop.interface gtk-theme 'Adapta-Nokto'
    gsettings set org.cinnamon.theme name 'Adapta-Nokto'
fi
if [ "$int" = "Dark (Compact)" ]; then
    gsettings set org.cinnamon.desktop.wm.preferences theme 'Adapta-Nokto-Eta'
    gsettings set org.cinnamon.desktop.interface gtk-theme 'Adapta-Nokto-Eta'
    gsettings set org.cinnamon.theme name 'Adapta-Nokto'
fi
